import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { createInstrumenter } from 'istanbul-lib-instrument';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
// Coverage build: a one-shot production-like build whose `src/**` modules are
// Istanbul-instrumented so the wdio (Electron) run populates `window.__coverage__`.
// See specs/ui-map.md → "Testing the UI layer" and the test:coverage:e2e scripts.
const coverage = (process.argv[2] === "coverage");

const PLUGIN_ID = 'vault-share';
const PLUGIN_FILES = ['main.js', 'manifest.json', 'styles.css'];
// Gitignored, per-developer: a JSON array of vault root paths to auto-deploy
// into on every `npm run dev` rebuild. Absent ⇒ no auto-deploy (CI default).
const DEV_VAULTS_CONFIG = 'dev-vaults.local.json';

/** Read the optional list of vault roots to deploy into during `npm run dev`. */
function readDevVaults() {
	if (!existsSync(DEV_VAULTS_CONFIG)) return [];
	try {
		const parsed = JSON.parse(readFileSync(DEV_VAULTS_CONFIG, 'utf8'));
		if (!Array.isArray(parsed)) {
			console.warn(`[dev-deploy] ${DEV_VAULTS_CONFIG} must be a JSON array of vault paths; ignoring`);
			return [];
		}
		// Expand a leading ~ to the home directory.
		return parsed.map(p => p.replace(/^~(?=$|\/)/, homedir()));
	} catch (err) {
		console.warn(`[dev-deploy] failed to read ${DEV_VAULTS_CONFIG}: ${err.message}`);
		return [];
	}
}

/**
 * esbuild plugin: after each successful (dev/watch) rebuild, copy the plugin
 * files into each configured vault's plugin folder. Skipped entirely in
 * production builds and when no `dev-vaults.local.json` is present.
 */
const devDeployPlugin = {
	name: 'dev-deploy',
	setup(build) {
		const vaults = readDevVaults();
		if (vaults.length > 0) {
			console.log(`[dev-deploy] watching → ${vaults.join(', ')}`);
		}
		build.onEnd(result => {
			if (result.errors.length > 0) return;  // never deploy a broken build
			for (const vault of vaults) {
				const dir = join(vault, '.obsidian', 'plugins', PLUGIN_ID);
				try {
					mkdirSync(dir, { recursive: true });
					for (const file of PLUGIN_FILES) copyFileSync(file, join(dir, file));
					console.log(`[dev-deploy] → ${dir}`);
				} catch (err) {
					console.warn(`[dev-deploy] could not deploy to ${dir}: ${err.message}`);
				}
			}
		});
	},
};

/**
 * esbuild plugin: Istanbul-instrument every `src/**` TypeScript module (test
 * files and node_modules excluded) so the bundled `main.js` records line/branch
 * coverage into the global `__coverage__` at runtime. Each file is transpiled
 * TS→JS with a sourcemap first, then instrumented against that map, so coverage
 * attributes back to the original `.ts` source (same absolute paths vitest uses,
 * which is what lets the two reports merge).
 */
const coveragePlugin = {
	name: 'istanbul-coverage',
	setup(build) {
		// Instrument the ORIGINAL TypeScript directly (parsed with the `typescript`
		// plugin) rather than transpiled JS. istanbul records statement positions
		// in the coordinates of the code it parses, so instrumenting TS keeps the
		// recorded line/branch positions in TS coordinates — matching vitest's
		// istanbul provider, which is what makes the line-union combined report
		// (scripts/coverage-combine.mjs) coherent. esbuild's `ts` loader then
		// strips the types and bundles, leaving the inserted counters intact.
		const instrumenter = createInstrumenter({
			esModules: true,
			compact: false,
			coverageVariable: '__coverage__',
			parserPlugins: [
				'typescript',
				'asyncGenerators', 'bigInt', 'classProperties', 'classPrivateProperties',
				'classPrivateMethods', 'dynamicImport', 'importMeta', 'nullishCoalescingOperator',
				'numericSeparator', 'objectRestSpread', 'optionalCatchBinding', 'optionalChaining',
				'topLevelAwait',
			],
		});
		build.onLoad({ filter: /\.ts$/ }, (args) => {
			if (args.path.includes('node_modules') || /\.test\.ts$/.test(args.path)) return undefined;
			const source = readFileSync(args.path, 'utf8');
			const code = instrumenter.instrumentSync(source, args.path);
			return { contents: code, loader: 'ts' };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	// coverage → istanbul instrumentation; dev/watch → auto-deploy; prod → neither.
	plugins: coverage ? [coveragePlugin] : prod ? [] : [devDeployPlugin],
});

if (prod || coverage) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
