import tseslint from 'typescript-eslint';
import obsidianmd from "eslint-plugin-obsidianmd";
import globals from "globals";
import { globalIgnores } from "eslint/config";

export default tseslint.config(
	{
		languageOptions: {
			globals: {
				...globals.browser,
			},
			parserOptions: {
				projectService: {
					allowDefaultProject: [
						'eslint.config.js',
						'manifest.json'
					]
				},
				tsconfigRootDir: import.meta.dirname
			},
		},
	},
	...obsidianmd.configs.recommended,
	{
		// eslint-plugin-obsidianmd@0.3.0 enables the *type-checked*
		// `no-plugin-as-component` rule in its global (non-file-scoped) rule set,
		// so it also runs on package.json / manifest.json — where the JSON parser
		// has no TS services and the rule throws. Disable it for JSON; it remains
		// active for *.ts (the recommended config's typed block re-enables it).
		files: ["**/*.json"],
		rules: { "obsidianmd/no-plugin-as-component": "off" },
	},
	{
		// Project convention: a leading underscore marks an intentionally-unused
		// binding. 0.3.0 pulls in tseslint's type-checked config which enables
		// no-unused-vars, so restore the underscore exemption.
		files: ["**/*.ts"],
		rules: {
			"@typescript-eslint/no-unused-vars": ["warn", {
				argsIgnorePattern: "^_",
				varsIgnorePattern: "^_",
				caughtErrorsIgnorePattern: "^_",
			}],
		},
	},
	{
		// Test setup legitimately seeds globals (e.g. fake-indexeddb via
		// `globalThis.indexedDB`); the popout-window guidance behind no-global-this
		// is a production-UI concern that does not apply to the test environment.
		files: ["**/*.test.ts"],
		rules: { "obsidianmd/no-global-this": "off" },
	},
	globalIgnores([
		"node_modules",
		"dist",
		// Non-source JSON. eslint v9 traverses `.json` because obsidianmd registers
		// `package.json` as a linted file, but only package.json gets the JSON
		// language — every other `.json` falls through to the JS parser and fails
		// (JSONC/plain JSON isn't JS). These are tooling configs, not plugin source;
		// manifest validation still runs (obsidianmd reads manifest.json via fs in
		// the package.json lint context).
		"manifest.json",
		"package-lock.json",
		"tsconfig.json",
		"tsconfig.wdio.json",
		"typedoc.json",
		".markdownlint.json",
		".nycrc.json",
		".vscode/**",
		".claude/**",
		"persistentTestResources/**",
		"coverage/**",      // generated by vitest coverage — not part of the source project
		"coverage-e2e/**",  // generated by nyc (e2e coverage report)
		"coverage-all/**",  // generated combined coverage report
		".nyc_output/**",   // raw e2e coverage counters
		".coverage-combined/**",
		"scripts/**",       // build/coverage helper scripts (node .mjs, not plugin source)
		"docs/**",          // generated by typedoc — not part of the source project
		"esbuild.config.mjs",
		"eslint.config.js",
		"version-bump.mjs",
		"versions.json",
		"main.js",
		"vitest.config.ts",
		"wdio.conf.mts",
		"wdio.multiremote.conf.mts",
		"tests/wdio/**",
		"tests/playground/**",
		"test-resources/**",  // wdio sandbox vaults + plugin build artifacts, not plugin source
		"google-auth-relay/**",
		"vitest.playground.config.ts",
		"deploy.mjs",
		"new-credential.mjs",
		"scripts/**",       // Node CLI helpers (e.g. obsidian-cdp.mjs), not plugin source
	]),
);
