import tseslint from 'typescript-eslint';
import obsidianmd from "eslint-plugin-obsidianmd";
import globals from "globals";
import { globalIgnores } from "eslint/config";

export default tseslint.config(
	{
		languageOptions: {
			globals: {
				...globals.browser,
			},
			parserOptions: {
				projectService: {
					allowDefaultProject: [
						'eslint.config.js',
						'manifest.json'
					]
				},
				tsconfigRootDir: import.meta.dirname,
				extraFileExtensions: ['.json']
			},
		},
	},
	...obsidianmd.configs.recommended,
	globalIgnores([
		"node_modules",
		"dist",
		"coverage/**",      // generated by vitest coverage — not part of the source project
		"coverage-e2e/**",  // generated by nyc (e2e coverage report)
		"coverage-all/**",  // generated combined coverage report
		".nyc_output/**",   // raw e2e coverage counters
		".coverage-combined/**",
		"scripts/**",       // build/coverage helper scripts (node .mjs, not plugin source)
		"docs/**",          // generated by typedoc — not part of the source project
		"esbuild.config.mjs",
		"eslint.config.js",
		"version-bump.mjs",
		"versions.json",
		"main.js",
		"vitest.config.ts",
		"wdio.conf.mts",
		"wdio.multiremote.conf.mts",
		"tests/wdio/**",
		"tests/playground/**",
		"test-resources/**",  // wdio sandbox vaults + plugin build artifacts, not plugin source
		"google-auth-relay/**",
		"vitest.playground.config.ts",
		"deploy.mjs",
		"new-credential.mjs",
		"scripts/**",       // Node CLI helpers (e.g. obsidian-cdp.mjs), not plugin source
	]),
);
